version: "3.3"
services:
  db:
    container_name: db
    image: postgres:11.6
    restart: always
    environment:
      - POSTGRES_USER=wisemen
      - POSTGRES_PASSWORD=wisemen
      - POSTGRES_DB=wisemen
    ports:
      - "5432:5432"
    volumes:
      - ./docker-compose-data/pgdata:/var/lib/postgresql/data

  monolith:
    container_name: monolith
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      - SERVER_PORT=3000
      - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/wisemen?useUnicode=true&characterEncoding=UTF-8
      - JDBC_DATABASE_USERNAME=wisemen
      - JDBC_DATABASE_PASSWORD=wisemen
    ports:
      - "3000:3000"
    depends_on:
      - db
